config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^jediorder/', include('jediorder.urls', namespace='jediorder')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jediorder/urls.py
from django.conf.urls import url
from jediorder.views import JediListView, CandidateCreateView

from . import views


urlpatterns = [
    url(r'^jedi/$', JediListView.as_view(), name='jedi'),
    url(r'^candidate/$', CandidateCreateView.as_view(), name='candidate'),
    url(r'^candidate/new/$', views.new_candidate_view, name='create-candidate'),
    url(r'^quiz/(?P<id>[0-9]+)/$', views.quiz_view, name='padawan-quiz'),
    url(r'^quiz/new/$', views.create_result_quiz_view, name='create-quiz'),
    url(r'^jedi/(?P<id>[0-9]+)/$', views.candidates_in_padawan_view, name='candidates-in-padawan'),
    url(r'^jedi/padawan/$', views.choice_padawan_view, name='choice-padawan'),
]

jediorder/models/candidate.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Candidate(models.Model):
    name = models.CharField(
        max_length=25, verbose_name=_("Имя"),
    )
    planet = models.ForeignKey(
        'jediorder.Planet', verbose_name=_("Планета обитания"),
    )
    age = models.IntegerField(
        verbose_name=_("Возраст")
    )
    email = models.EmailField(
        verbose_name=_("Email")
    )
    padawan = models.BooleanField(default=False, verbose_name=_("Падаван?"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Кандидат")
        verbose_name_plural = _("Кандидаты")

jediorder/models/jedi.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Jedi(models.Model):
    name = models.CharField(
        max_length=25, verbose_name=_("Имя")
    )
    planet = models.ForeignKey(
        'jediorder.Planet', verbose_name=_("Планета обучения")
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Джедай")
        verbose_name_plural = _("Джедаи")

jediorder/models/planet.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Planet(models.Model):
    name = models.CharField(max_length=25, verbose_name=_("Наименование"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Планета")
        verbose_name_plural = _("Планеты")

jediorder/models/questions.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Question(models.Model):
    question = models.TextField(verbose_name=_("Вопрос"))

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = _("Вопрос")
        verbose_name_plural = _("Вопросы")


class Answer(models.Model):
    answer = models.NullBooleanField(verbose_name=_("Ответ"))
    question = models.ForeignKey(
        'jediorder.Question', verbose_name=_("Вопрос")
    )
    quiz = models.ForeignKey(
        'jediorder.Quiz', verbose_name=_("Тестовое испытание")
    )

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = _("Ответ")
        verbose_name_plural = _("Ответы")


class Quiz(models.Model):
    candidate_id = models.ForeignKey(
        'jediorder.Candidate', verbose_name=_("Код ордена")
    )
    questions = models.ManyToManyField(
        'jediorder.Question', verbose_name=_("Вопросы")
    )

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = _("Тестовое испытание")
        verbose_name_plural = _("Тестовые испытания")

config/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'base.html')

jediorder/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView
from django.views.decorators.csrf import csrf_exempt

from dbmail import send_db_mail
from .models.questions import Answer, Question, Quiz
from .models.candidate import Candidate
from .models.planet import Planet
from .models.jedi import Jedi


class JediListView(ListView):

    context_object_name = 'jedi_list'
    queryset = Jedi.objects.all().select_related('planet').order_by('planet')
    template_name = 'jediorder/jedi_list.html'


def candidates_in_padawan_view(request, id):
    quiz_list = Quiz.objects.all()
    questions = Question.objects.filter(id__in=quiz_list)
    candidates = Candidate.objects.filter(
        planet__id=id, padawan=False,
        id__in=quiz_list.values('candidate_id')
    )
    results = Answer.objects.select_related('quiz', 'question').filter(
        quiz__in=quiz_list
    )
    return render(request, 'jediorder/candidates_in_padawans.html', {
        'candidates': candidates,
        'results': results,
        'questions': questions

    })


@csrf_exempt
def choice_padawan_view(request):
    candidate_id = request.POST.get('candidate_id')
    candidate = Candidate.objects.get(id=candidate_id)
    candidate.padawan = True
    candidate.save()

    context = {'username': candidate.name}

    send_db_mail(
        'template-for-padawans', candidate.email,
        context, use_celery=True
    )

    return render(request, 'jediorder/candidates_in_padawans.html')


class CandidateCreateView(CreateView):
    model = Candidate
    fields = ['name', 'age', 'planet', 'email']


@csrf_exempt
def new_candidate_view(request):
    id = []
    if request.method == 'POST':
        name = request.POST.get('name')
        age = request.POST.get('age')
        planet = request.POST.get('planet')
        email = request.POST.get('email')
        new_candidate = Candidate.objects.create(
            name=name, age=age, email=email,
            planet=Planet.objects.get(id=planet)
        )
        id.append(new_candidate.id)
    candidate = Candidate.objects.get(id=id[0])
    return redirect('jediorder:padawan-quiz', id=candidate.id)


@csrf_exempt
def quiz_view(request, id):
    questions = Question.objects.all()
    candidate = Candidate.objects.get(id=id)
    return render(request, 'jediorder/quiz.html', {
        'questions': questions, 'candidate': candidate
    })


@csrf_exempt
def create_result_quiz_view(request):
    data = {}
    for key, value in request.POST.items():
        data[key] = value
    candidate = Candidate.objects.get(id=data['candidate_id'])
    questions = Question.objects.all()

    if Quiz.objects.filter(candidate_id=candidate.id).exists() is True:
        for question in questions:
            Answer.objects.create(
                question=question, answer=data[str(question.id)],
                quiz=Quiz.objects.get(candidate_id=candidate.id)
            )
    else:
        quiz = Quiz(candidate_id=candidate)
        quiz.save()
        for question in questions:
            quiz.questions.add(question.id)
            quiz.save()
        for question in questions:
            Answer.objects.create(
                question=question, answer=data[str(question.id)],
                quiz=quiz
            )

    return render(request, 'jediorder/end_test.html')

templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="ru">

    {%  include 'blocks/head.html'  %}

    <body>

        {% include 'blocks/header.html' %}


        {% block content %}


        {% endblock %}

        {% include 'blocks/footer.html' %}


    </body>

</html>

templates/blocks/head.html
{% load staticfiles %}
{% load bootstrap3 %}

<head>
    <meta charset="UTF-8">
    <title>Академия джедаев</title>

    <script src="{% bootstrap_jquery_url %}"></script>
    {% bootstrap_javascript %}
    {% bootstrap_css %}

    {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'styles/base.css' %}">
</head>

templates/blocks/header.html
{% load staticfiles %}
{% load bootstrap3 %}

<header>

    <div class="menu">
        <ul class="nav nav-pills nav-justified navbar-inverse">
            <li id="jedi"><a href="{% url 'jediorder:jedi' %}"><b>Джедай</b></a></li>
            <li id="candidate"><a href="{% url 'jediorder:candidate' %}"><b>Кандидат</b></a></li>
        </ul>
    </div>

</header>

templates/jediorder/candidate_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <form action="{% url 'jediorder:create-candidate' %}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% bootstrap_form form %}
            <input class="btn btn-danger" type="submit" value="Далее"/>
        </form>
    </div>
{% endblock %}

templates/jediorder/candidates_in_padawans.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <table class="table">
            <tr>
                <th class="col-md-2">Имя</th>
                <th class="col-md-2">Возраст</th>
                <th class="col-md-2">Испытание</th>
                <th class="col-md-2">Зачислить в падаваны?</th>
            </tr>
        {% for candidate in candidates %}
            <tr>
                <th class="col-md-2">{{ candidate.name }}</th>
                <th class="col-md-2">{{ candidate.age }}</th>
                <th class="col-md-2">
                    <button class="btn btn-info" id="b{{ candidate.id }}">Посмотреть результаты</button>
                    <div id="rb{{ candidate.id }}" style="display: none">
                    {% for result in results %}
                        {% if result.quiz.candidate_id.id == candidate.id %}
                            <p>{{ result.question.question }} - {{ result.answer|yesno:"Да, Нет, Затрудняюсь ответить" }}</p>
                        {% endif %}
                    {% endfor %}
                    </div>
                </th>
                {% csrf_token %}
                <th class="col-md-2" id="data" data-id="{{ candidate.id }}" data-url="{% url 'jediorder:choice-padawan' %}">
                    <button class="btn btn-success" id="button_padawan">Зачислить</button>
                </th>
            </tr>
        {% endfor %}
        </table>
    </div>

    {% load static %}
    {% block javascript %}
        <script src="{% static 'scripts/base.js' %}"></script>
    {% endblock %}

{% endblock %}

templates/jediorder/end_test.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
     <div class="alert alert-success">
         <h4>Спасибо за выполнение теста!</h4>
         <h5>Как только джедаи рассмотрять результаты вашего испытания, вам придет уведомление.</h5>
     </div>
{% endblock %}

templates/jediorder/jedi_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="container">
        <table class="table table-hover">
            <tr>
                <th class="col-md-offset-4"><p>Джедай</p></th>
                <th class="col-md-4"><p>Планета обучения</p></th>
            </tr>
        {% for jedi in jedi_list %}
            <tr>
                <th class="col-md-offset-4">
                    <a href="{% url 'jediorder:candidates-in-padawan' id=jedi.planet.id %}">
                        {{ jedi.name }}
                    </a>
                </th>
                <th class="col-md-4">
                    <p>{{ jedi.planet }}</p>
                </th>
            </tr>
        {% endfor %}
        </table>
    </div>
{% endblock %}

templates/jediorder/quiz.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container">
        {% csrf_token %}
        <form method="POST" action="{% url 'jediorder:create-quiz' %}">
            <input type="hidden" name="candidate_id" value="{{ candidate.id }}">
            {% for question in questions %}
                <p id="{{ question.id }}"><b>{{ question.question }}</b></p>
                <p>
                    <label class="radio-inline">
                        <input type="radio" name="{{ question.id }}" value="True" required> Да
                    </label>
                    <label class="radio-inline">
                        <input type="radio" name="{{ question.id }}" value="False"> Нет
                    </label>
                    <label class="radio-inline">
                        <input type="radio" name="{{ question.id }}" value="None"> Затрудняюсь ответить
                    </label>
                </p>
            {% endfor %}
            <input class="btn btn-danger" type="submit" value="Отправить">
        </form>
    </div>

{% endblock %}